### ISSUE TITLE
Invalid judgement in audioVideoFrameTimestampComparator

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-pic#116]
https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/5efcd01b75069716e1ace2a9fc00b729a2d1573f/src/client/src/FrameOrderCoordinator.c#L128

When mkvTimestamp1 and mkvTimestamp2 are equal, firstFrameFirst must be true here.

https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/5efcd01b75069716e1ace2a9fc00b729a2d1573f/src/client/src/FrameOrderCoordinator.c#L133-L134

**Comment by disa6302** [comment]
Oh yes! Based on the comment, this looks like a bug. @MushMal , what do you think?

**Comment by MushMal** [comment]
Agree that the logic is odd. Don't know/remember why this was added like that.

Please review #118
