### ISSUE TITLE
Relax check for DTS ordering in Content View

### ISSUE THREAD

**Issue by sharadrj** [awslabs/amazon-kinesis-video-streams-pic#14]
In content view, we have the check that the frame decoding timestamp should be greater or equal to the previous frame timestamp, plus the previous frame duration: `DTS(n) >= DTS(n-1) + Duration(n-1)`.  

This is more restrictive than absolutely necessary. It would be sufficient to only check for monotonically increasing timestamps: DTS(n) >= DTS(n-1)

**Comment by MushMal** [comment]
63b62eade7a1a58f532d8f21d0668961cccbc838 fixes
