### ISSUE TITLE
[CONTRIBUTION] Frame is an anonymous struct

### ISSUE THREAD

**Issue by daveisfera** [awslabs/amazon-kinesis-video-streams-pic#167]
** Describe the issue you are trying to solve **
`Frame` currently doesn't have a name, so it can't be forward declared

** Details of the changes **
Give `Frame` a name (`__Frame`) so it's not anonymous

** Test cases **
N/A

** Additional context **
Matches the definition of the other `struct`s in the code

**Comment by daveisfera** [comment]
There already is one and it's linked to in this issue already, but here it is again for fun:
https://github.com/awslabs/amazon-kinesis-video-streams-pic/pull/168/files

**Comment by daveisfera** [comment]
Possible to merge the above request so we don't have to keep carrying a patch for it?

**Comment by niyatim23** [comment]
Hi @daveisfera, apologies for the delay. The PR looks good, can you please open it against `develop` branch. We accept contributions through that one. Once all the checks pass, it will be merged. Thank you for your contribution.

**Comment by niyatim23** [comment]
Merged into `develop`
