### ISSUE TITLE
[QUESTION] update opus audio by kinesis

### ISSUE THREAD

**Issue by liuyi96** [awslabs/amazon-kinesis-video-streams-pic#179]
I am trying to upload opus audio using kvs, does kvs support this type of audio? Which CODECID and content type should I use?
`/**
 * Constant definition for some known content types
 */
#define MKV_H264_CONTENT_TYPE             ((PCHAR) "video/h264")
#define MKV_H265_CONTENT_TYPE             ((PCHAR) "video/h265")
#define MKV_X_MKV_VIDEO_CONTENT_TYPE      ((PCHAR) "video/x-matroska")
#define MKV_X_MKV_AUDIO_CONTENT_TYPE      ((PCHAR) "audio/x-matroska")
#define MKV_AAC_CONTENT_TYPE              ((PCHAR) "audio/aac")
#define MKV_ALAW_CONTENT_TYPE             ((PCHAR) "audio/alaw")
#define MKV_MULAW_CONTENT_TYPE            ((PCHAR) "audio/mulaw")
#define MKV_AVC_CONTENT_TYPE              ((PCHAR) "video/avc")
#define MKV_HEVC_CONTENT_TYPE             ((PCHAR) "video/hevc")
#define MKV_H264_AAC_MULTI_CONTENT_TYPE   ((PCHAR) "video/h264,audio/aac")
#define MKV_H264_MULAW_MULTI_CONTENT_TYPE ((PCHAR) "video/h264,audio/mulaw")
/**
 * Constant definitions for some known codec IDs
 */
#define MKV_FOURCC_CODEC_ID         ((PCHAR) "V_MS/VFW/FOURCC")
#define MKV_H264_AVC_CODEC_ID       ((PCHAR) "V_MPEG4/ISO/AVC")
#define MKV_H265_HEVC_CODEC_ID      ((PCHAR) "V_MPEGH/ISO/HEVC")
#define MKV_AAC_MPEG4_MAIN_CODEC_ID ((PCHAR) "A_AAC/MPEG4/MAIN")
#define MKV_AAC_CODEC_ID            ((PCHAR) "A_AAC")
#define MKV_PCM_CODEC_ID            ((PCHAR) "A_MS/ACM")
#define MKV_PCM_INT_LIT_CODEC_ID    ((PCHAR) "A_PCM/INT/LIT")
#define MKV_PCM_INT_BIG_CODEC_ID    ((PCHAR) "A_PCM/INT/BIG")
#define MKV_PCM_FLOAT_IEEE_CODEC_ID ((PCHAR) "A_PCM/FLOAT/IEEE")`

**Comment by disa6302** [comment]
Producer SDK does not support Opus. We hav Opus support in WebRTC.

**Comment by peterxli** [comment]
> Producer SDK does not support Opus. We hav Opus support in WebRTC.

Does opus, which uses ogg encapsulation, also not support it？

**Comment by peterxli** [comment]
> Producer SDK does not support Opus. We hav Opus support in WebRTC.
opus is currently a free, dynamically adjustable, high-fidelity coding algorithm. May I ask when the SDK will support it
