### ISSUE TITLE
Error when building on Windows (cygwin)

### ISSUE THREAD

**Issue by danteblink** [awslabs/amazon-kinesis-video-streams-pic#180]
When building the library using `make` i got the following error:

```
In file included from /cygdrive/c/amazon-kinesis-video-streams-pic-master/src/client/include/com/amazonaws/kinesis/video/client/Include.h:13,
                 from /cygdrive/c/amazon-kinesis-video-streams-pic-master/src/client/src/Include_i.h:16,
                 from /cygdrive/c/amazon-kinesis-video-streams-pic-master/src/client/src/AckParser.c:6:
/cygdrive/c/amazon-kinesis-video-streams-pic-master/src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h:569:10: fatal error: sys/prctl.h: No such file or directory
  569 | #include <sys/prctl.h>
```

Apparently, prctl.h is a Linux header, but I can´t find a workaround to compile it on Windows.

**Comment by niyatim23** [comment]
Hi @danteblink, please refer to [this](https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/.github/workflows/ci.yml#L169-L179) working Windows build from our CI for your setup

Closing assuming answered, feel free to re-open / create new issues
