### ISSUE TITLE
Use monotonic timer instead of GETTIME for all timeout

### ISSUE THREAD

**Issue by ek9852** [awslabs/amazon-kinesis-video-streams-pic#28]
GETTIME is not monotonic, it will be affected by ntp jump or skew or even adjust backward if the start date/time is incorrect..
Also ntp protocol is not secure, a man in the middle might fire a time in the future then fire a time back to normal.
Then those codes relies on GETTIME to do time out will not timeout and might cause unexpected behavior.

I have a patch (https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/pull/316)  in amazon-kinesis-video-streams-producer-sdk-cpp to add a function GETMONOTONICTIME and fix the pthread_cond_timedwait which used in linux to use  monotonic timer.

But there are still code in the amazon-kinesis-video-streams-producer-sdk-cpp and webrtc-sdk still using GETTIME for timeout.

**Comment by MushMal** [comment]
Sorry this took so long. Here is what we have currently. We have introduced a new GETREALTIME macro that's used only in CVAR implementation for wait. This is necessary as most implementations of cvar wait rely on the realtime clock. The intent is to not propagate this API further up the callback chain to C Producer/JNI/etc..

For the use case where the time functionality needs to be overwritten:

* At the source level change: Replace GETTIME macro to point to a new function of your choice and implement it.
* As a callback: Specify a new time callback in PIC that will be used for time operations other than CVAR waiting.
    * JNI: Overwrite the KVS wrapper API for time
    * C Producer: Specify custom time callback in PlatformCallbacks
    * C++: Same as above

Resolving for now. Please cut a separate issue if need further info/help
