### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by HsaeedAhmad** [awslabs/amazon-kinesis-video-streams-pic#35]
I'm facing 94 syntax error during the build but when i checked the file there is no syntax error like this.

f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(250): erro
r C2099: initializer is not a constant [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-na
tive-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(251): erro
r C2143: syntax error: missing '{' before '+=' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-
video-native-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(251): erro
r C2059: syntax error: '+=' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build
kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(253): erro
r C2059: syntax error: 'do' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build
kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(253): erro
r C2059: syntax error: 'while' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-bui
ld\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(256): erro
r C2143: syntax error: missing '{' before '++' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-
video-native-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(256): erro
r C2059: syntax error: '++' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build
kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(259): erro
r C2059: syntax error: '{' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build\k
vspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(259): erro
r C2059: syntax error: ')' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build\k
vspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(260): erro
r C2143: syntax error: missing '{' before '+=' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-
video-native-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(260): erro
r C2059: syntax error: '+=' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build
kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(264): erro
r C2143: syntax error: missing '{' before '+=' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-
video-native-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(264): erro
r C2059: syntax error: '+=' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build
kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(267): erro
r C2065: 'pCurPnt': undeclared identifier [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video
-native-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(267): erro
r C2065: 'pAdaptedCpd': undeclared identifier [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-v
ideo-native-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(267): erro
r C2099: initializer is not a constant [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-na
tive-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(269): erro
r C2143: syntax error: missing '{' before ':' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-v
ideo-native-build\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(269): erro
r C2059: syntax error: ':' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build\k
vspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(275): erro
r C2059: syntax error: 'if' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build
kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(279): erro
r C2059: syntax error: 'return' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-bu
ild\kvspic.vcxproj]
3>f:\batech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-pic\src\mkvgen\src\naladapter.c(280): erro
r C2059: syntax error: '}' [F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build\k
vspic.vcxproj]
Generating Code...
3>Done Building Project "F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build\kvspic
.vcxproj" (default targets) -- FAILED.
1>Done Building Project "F:\BATech\amazon-kinesis-video-streams-producer-sdk-cpp\kinesis-video-native-build\pic_te
st.vcxproj" (default targets) -- FAILED.

Build FAILED.

**Comment by MushMal** [comment]
@HsaeedAhmad can you confirm that you are building 'clean' on Windows using native VC?

**Comment by HsaeedAhmad** [comment]
I was trying to build on windows but due to lots of issues i switched on linux  now sdk producer build successfully but below error is occuring  when i run this command "AWS_ACCESS_KEY_ID=<ACCESS_KEY> AWS_SECRET_ACCESS_KEY=<SECRET_KEY> ./kinesis_video_gstreamer_sample_app <my_rtsp_url> my-stream" 

[DEBUG] [02-04-2020 13:18:58:279.891 GMT] describeStreamCurlHandler(): DescribeStream API response:
[INFO ] [02-04-2020 13:18:58:284.076 GMT] describeStreamResultEvent(): Describe stream result event.
[ERROR] [02-04-2020 13:19:04:694.561 GMT] createKinesisVideoStreamSync(): Failed to create Kinesis Video Stream - timed out.
[INFO ] [02-04-2020 13:19:04:699.280 GMT] freeKinesisVideoStream(): Freeing Kinesis Video stream.
[ERROR] [02-04-2020 13:19:05:203.985 GMT]  Unable to create Kinesis Video stream. rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov Error status: 0xf
[INFO ] [02-04-2020 13:19:05:206.124 GMT] Freeing Kinesis Video Stream rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
[INFO ] [02-04-2020 13:19:05:209.207 GMT] freeKinesisVideoStream(): Freeing Kinesis Video stream.
[ERROR] [02-04-2020 13:19:05:209.907 GMT] Failed to initialize kinesis video with an exception:  Unable to create Kinesis Video stream. rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov Error status: 0xf
[INFO ] [02-04-2020 13:19:05:211.021 GMT] freeKinesisVideoClient(): Freeing Kinesis Video Client
[WARN ] [02-04-2020 13:19:05:211.790 GMT] curlApiCallbacksShutdownActiveRequests(): pActiveRequests hashtable is empty
[DEBUG] [02-04-2020 13:19:05:613.746 GMT] freeKinesisVideoClientInternal(): Total allocated memory 0
[WARN ] [02-04-2020 13:19:05:615.160 GMT] curlApiCallbacksShutdown(): curlApiCallbacksShutdown called when already in progress of shutting down

**Comment by HsaeedAhmad** [comment]
All i'm doing after ./install-script but when i run ./gstreamer-plugin-install-script this show me below error guide which i follow https://diycode.cc/projects/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp  
kinesis-video-gstreamer-plugin/tst/gstkvstest.cpp:1:10: fatal error: gstkvssink.h: No such file or directory
 #include "gstkvssink.h" //import this first, or will cause build error on Mac
          ^~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/gstkvsplugintest.dir/build.make:62: recipe for target 'CMakeFiles/gstkvsplugintest.dir/home/saeed/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-gstreamer-plugin/tst/gstkvstest.cpp.o' failed
make[3]: *** [CMakeFiles/gstkvsplugintest.dir/home/saeed/amazon-kinesis-video-streams-producer-sdk-cpp/kinesis-video-gstreamer-plugin/tst/gstkvstest.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/gstkvsplugintest.dir/all' failed
make[2]: *** [CMakeFiles/gstkvsplugintest.dir/all] Error 2
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/gstkvsplugintest.dir/rule' failed
make[1]: *** [CMakeFiles/gstkvsplugintest.dir/rule] Error 2
Makefile:118: recipe for target 'gstkvsplugintest' failed
make: *** [gstkvsplugintest] Error 2

**Comment by MushMal** [comment]
@HsaeedAhmad this is a separate issue from what you reported on Windows. We will track the windows issue separately. I suggest opening different issues for different things so we can proprly track and respond.

There is an error attempting to create a stream object:

[ERROR] [02-04-2020 13:19:04:694.561 GMT] createKinesisVideoStreamSync(): Failed to create Kinesis Video Stream - timed out.
[INFO ] [02-04-2020 13:19:04:699.280 GMT] freeKinesisVideoStream(): Freeing Kinesis Video stream.
[ERROR] [02-04-2020 13:19:05:203.985 GMT] Unable to create Kinesis Video stream. rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov Error status: 0xf

The logs are not verbose enough to see what the root cause is. Likely scenarios are either networking or simply the permissions are not set properly.

More information on how to set the permissions is here: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-iam.html

You can enable debug level logging in the env variable or directly in the code:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/4534e876cf508b8141ce87eeab7c83963ebdc32c/README.md#setup-desired-log-level

Also, it seems that you are attempting to use the CPP library assets - might make sense to open an issue in that repository.

The third issue is again a separate issue and is related to either build failing or you not specifying the correct paths. You could try to use min_install_script to pull down the dependencies instead of building them. There is a good readme in cpp repository.

**Comment by Sean-Der** [comment]
Hey @HsaeedAhmad 

This repo didn't build on Windows with MSVC before, but it does now with https://github.com/awslabs/amazon-kinesis-video-streams-pic/pull/49 You can also look in our travis builder and see it actively working.

Or other repos might not work with Windows yet, but I am going to test and fix them now.

Thanks for checking out KVS!
