### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by Sean-Der** [awslabs/amazon-kinesis-video-streams-pic#4]
* Top level explanation
* List of high level features (mkvgen, hashmap etc...)

**Comment by RalphCorderoy** [comment]
Yes please, I'm unclear if this might be of use in a project that's using Amazon FreeRTOS on a Texas Instruments CC3220 that wants to stream JPEGs from a few cameras, so need STUN, TURN, WebRTC, etc., and quickly being able to ignore this project if it's not suitable would be useful.

**Comment by MushMal** [comment]
@RalphCorderoy perhaps you can describe your scenario here or by opening a separate issue on this repository or on webrtc embedded SDK repository so we can help guiding you. You could also send questions to kinesis-video-support@amazon.com

**Comment by hassanctech** [comment]
README is in a pretty good state now, closing.
