### ISSUE TITLE
Skip SEI NALu in getVideoWidthAndHeightFromH264SPS

### ISSUE THREAD

**Issue by MushMal** [awslabs/amazon-kinesis-video-streams-pic#43]
When processing H264 (similar issue with H265 potentially) we are extracting the width and height of the picture from the SPS in order to set MKV parameters. This is for Video H264 (and H265) only. The function assumes that the first NALu of the CPD is SPS whereas it might be SEI.

The fix is to check the first NALu and skip it if it's SEI and process SPS only.

**Comment by farleylai** [comment]
Hi @MushMal,

It seems like the SEI and multiple SPS/PPS in the key frame are handled.
I have a source giving key frames with NALUs as follows:
- key frame with SPS/PPS/SEI but no IDR followed by
- key frame with SPS/PPS/SPS/PPS/IDR

KVS SDK and the console do not return or show any errors this time.
Can you confirm that is the case?

**Comment by MushMal** [comment]
@farleylai the SDK attempts to validate only stuff that's absolutely necessary. The SDK passes along the data that it validates at the packaging layer to the backend. The similar strategy is on the backend, we try to validate only items that are needed for streamability, indexing and most importantly, correctness. So, multiple properly formed SPS/PPS/SEI should be OK from the packaging standpoint but you might also want to ensure that the player/playback solution you use downstream are OK.
The issue I opened is about trying to extract the width and height to set MKV video element width and height - these really are useless but some downstream players seem to care. Similar situation is for Audio content.

**Comment by farleylai** [comment]
@MushMal 
Sorry, I intended to post in the original issue, not here.
And agreed, this is a separate concern which is not in our use cases yet.

**Comment by MushMal** [comment]
Now it should work -> https://github.com/awslabs/amazon-kinesis-video-streams-pic/pull/68

I reverted the removal of the non-VCL NALu changes. We had an issue with an extra frame size bloat due to the extra zeroes

**Comment by MushMal** [comment]
Changes are in
