### ISSUE TITLE
Saved webm causes some video players such as VLC to stop immediately

### ISSUE THREAD

**Issue by farleylai** [awslabs/amazon-kinesis-video-streams-pic#44]
By specifying the timestamp range, the fragment list can be retrieved first. Next, the list of fragments can be sorted to retrieve the media by calling get_media_for_fragment_list() from a KVS stream.
The response payload can be read and saved in `webm`. However, when playing the webm using some players such as VLC and other front end JS video player, the playback ends immediately. The log message from VLC shows warning during [parsing mkv](https://github.com/strukturag/vlc-libde265/blob/5033259df597930ba8b21e3fefb812ef7a6596a9/src/demux/mkv/Ebml_parser.cpp#L234) as follows:

```
...
main debug: `file:///Users/farleylai/Downloads/video.mkv' successfully opened
main debug: Buffering 0%
mkv warning: Dummy element found 255665... skipping it
mkv warning: EOF
mkv warning: cannot get block EOF?
main debug: EOF reached
main debug: Stream buffering done (0 ms in 0 ms)
...
```

The normal process should show Buffering up to 100%. Nonetheless, `ffplay` can play the webm without issues but the use case requires the webm to be played by some other JS video players.
One workaround so far is to remux the webm in mkv or mp4 using ffmpeg. However, there seems like something missing in the fragment header or so.
Any ideas?

PS: This 10s video saved in webm is attached FYI. Tested using VLC 3.0.8 on macOS.

[video.tar.gz](https://github.com/awslabs/amazon-kinesis-video-streams-pic/files/4482868/video.tar.gz)

**Comment by MushMal** [comment]
@farleylai the attached video is a concatenation of the fragments retrieved by GetMedia call. Each is a MKV file fragment, containing MKV header. This will fail to playback on majority of playback engines. You can see that this is not a valid MKV by running `mkvinfo -v video.webm`

Kinesis Video Parser Library asset has a sample that parses the incoming GetMedia fragments and appends them into a file that will be valid single MKV file.

**Comment by MushMal** [comment]
Here is the reference to get more info: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/parser-library-write.html#parser-library-write-OSM

**Comment by farleylai** [comment]
Thanks for the clarification. 
The parser library seems only available in Java while most of our Lambdas are implemented in Python but we will manage.

**Comment by MushMal** [comment]
Indeed, it would be great if we had implemented the "consumer" side in a few languages which could be bound to Python for example.

In the meanwhile, if you get something generic, you are more than welcome to publish.

I am resolving this issue, please re-open if needed
