### ISSUE TITLE
Failed extracting video configuration from SPS with 32000015.

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-pic#55]
https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/bdcdfd0fed1e17bab9e6957ea9d0a1cecaddbb44/src/mkvgen/src/SpsParser.c#L243

The NALU type here is 0x67 and 0x27. but the SPS and PPS on my device is 0x47 and 0x48. Generally I get the NALU type by &0x1f, 0x07 means it is SPS.

**Comment by MushMal** [comment]
Interesting case... Your encoder produces SPS and PPS with nal_ref_idc = 2 - most of the encoders produce nal_ref_idc = 3 or 1.

I think we should properly parse this. The logic should be to check whether nal_ref_idc is NOT zero and not directly checking against hard-coded values for the entire field.

Are you willing to pitch in and send a PR? Let us know, we are always welcoming contributions!
