### ISSUE TITLE
Found unknown-length element with ID 0x18538067 

### ISSUE THREAD

**Issue by farleylai** [awslabs/amazon-kinesis-video-streams-pic#57]
After the video stream is uploaded to KVS, we have `ffmpeg` library to read/parse the `StreamBody` from the `GET_MEDIA` API response but there are constant warning messages as follows:

> Found unknown-length element with ID 0x18538067 at pos. 0x168b4e for which no syntax for parsing is available.

The number `0x18538067` is the segment ID defined in the spec of Matroska but the message seems to imply the size/length is missing. Could you clarify what may be the cause or missing?

PS: Video uploaded with KVS SDK 2.1.0.

**Comment by MushMal** [comment]
@farleylai the ffmpeg parser is hitting the segment header bits for the next fragment:
https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/mkvgen/src/MkvStatics.c#L24

When retrieving fragments on GetMedia, each fragment will be self-contained (like a file) MKV chunk so each will have it's own MKV header.


We have a sample in Java that strips out the consecutive headers and merges the segments: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/parser-library-write.html#parser-library-write-OSM

You could attempt to re-create something similar.

**Comment by farleylai** [comment]
Got it. It's a similar issue as before.
We now have a better idea of what to expect.
Thanks for the timely clarification.

**Comment by fazak** [comment]
> After the video stream is uploaded to KVS, we have `ffmpeg` library to read/parse the `StreamBody` from the `GET_MEDIA` API response but there are constant warning messages as follows:
> 
> > Found unknown-length element with ID 0x18538067 at pos. 0x168b4e for which no syntax for parsing is available.
> 
> The number `0x18538067` is the segment ID defined in the spec of Matroska but the message seems to imply the size/length is missing. Could you clarify what may be the cause or missing?
> 
> PS: Video uploaded with KVS SDK 2.1.0.

Hi @farleylai, I'm currently attempting something similar. Just curious whether you're able to replicate the Java parser
