### ISSUE TITLE
[Feature request] Customize time instead of system time

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-pic#61]
For my embedded device, the system has no time zone. After the program starts, it will maintain time zone internally. For example, after getting the utc time, it will add time zone offset to UTC time, then set it as system time. So if call _clock_gettime_, it will get a wrong value.
In order to get the right time, I have to repoint the pointer to a customized function which minus time offset.

https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/dadd46fee4fb9ae34c012ae4cd565b74e903859e/src/utils/src/Time.c#L3

```
    globalGetTime = OnGetUtcTimeUs;

    virtual uint64 OnGetUtcTimeUs()
    {
#if defined __MACH__ || defined __CYGWIN__
        struct timeval nowTime;
        if (0 != gettimeofday(&nowTime, NULL)) {
            return 0;
        }
        nowTime.tv_sec -= minutes[zone_]*60;
        return (uint64)nowTime.tv_sec * 1000LL * 1000LL + (uint64)nowTime.tv_usec;
#else
        struct timespec nowTime;
        clock_gettime(CLOCK_REALTIME, &nowTime);
        nowTime.tv_sec -= minutes[zone_]*60;
        return (uint64)nowTime.tv_sec * 1000LL * 1000LL + (uint64)nowTime.tv_nsec / 1000;
#endif
    }
```
After that, the program terminated immediatelly because of timeout. Actually it influences the _pthread_cond_timedwait_.
https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/dadd46fee4fb9ae34c012ae4cd565b74e903859e/src/utils/src/Mutex.c#L287

Here it should get real system time instead of customized time.
```
    UINT64 curTime = defaultGetTime();
```

**Comment by MushMal** [comment]
@Nomidia this is exactly the same as https://github.com/awslabs/amazon-kinesis-video-streams-pic/issues/28

The correct solution is to have two separate APIs - one for absolute time and the other for deltas like timeouts.

We don't have the ETA yet to fix but will be working on it soon

**Comment by MushMal** [comment]
Resolving: More info in #28
