### ISSUE TITLE
[Bug] No memory will be realloced when using instrumentedAllocatorsMemRealloc

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-pic#64]
https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/b3cc85a48a85abdd606adbec863f0a6f1c599306/src/utils/src/InstrumentedAllocators.c#L149-L151

When the ptr is null it will return NULL, it behaves differently from the system's realloc. In this case the function should  behave like malloc, assigning a new block of size bytes and returning a pointer to its beginning.

**Comment by MushMal** [comment]
@Nomidia thsnks for reporting. Indeed this is a bug. Please let us know if you are going to provide the fix for it with a targeted unit test. If not, I will put a quick fix with a test tonight

**Comment by Nomidia** [comment]
I haven't made any changes. I just use  _realloc_ temporarily.

**Comment by MushMal** [comment]
OK, Let me push a quick fix then
