### ISSUE TITLE
inline function or extern inline function.

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-pic#74]
Due to different definitions between C89 and C99, I am not sure the inline functions here are inline functions or external inline functions. 
Would you mind giving me some hints about the usage of inline functions in this sdk? 

Some error log is as below, and I fixed it by adding "-fgnu89-inline".
Thanks, 

iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/**-porting/kvs-pic/build$ make
Scanning dependencies of target kvspicUtils
[  1%] Building C object CMakeFiles/kvspicUtils.dir/src/utils/src/Allocators.c.o
In file included from /home/iotlab/scofield/_workspace/**-porting/kvs-pic/src/utils/src/Allocators.c:1:0:
/home/iotlab/scofield/_workspace/**-porting/kvs-pic/src/utils/src/Include_i.h:115:13: error: inline function 'putUnalignedInt64Le' declared but never defined [-Werror]
 INLINE VOID putUnalignedInt64Le(PVOID, INT64);
             ^~~~~~~~~~~~~~~~~~~
/home/iotlab/scofield/_workspace/**-porting/kvs-pic/src/utils/src/Include_i.h:114:13: error: inline function 'putUnalignedInt64Be' declared but never defined [-Werror]
 INLINE VOID putUnalignedInt64Be(PVOID, INT64);
             ^~~~~~~~~~~~~~~~~~~

**Comment by lherman-cs** [comment]
@MushMal probably has more context on this.

**Comment by MushMal** [comment]
The attempt is to inline some of the frequently called functionality like time. Unfortunately, due to the way we need to store function pointers for fast "headless" access, the compilers get confused. Most compilers that generate warnings will simply not inline the functions.

In your case, it seems that you were actually generating errors instead of warnings? Could you give us more context?

**Comment by ycyang1229** [comment]
Actually, it is a warning, but I enabled -Werror for the cross-compile in order to prevent unexpected fatal error from happening. My understanding is the inline function of C89 equals to the extern inline function of C99, and vice versa. So my first thinking is if this sdk does not use the function pointer calling inline functions, it will be fine. But if it uses the function pointer calling the inline functions, there may be a problem. I will code some verification code on my compiler and see what will happen.  Please correct me if I am wrong. thanks. :)

**Comment by ycyang1229** [comment]
Closing it and I will check the behavior of my compiler later. In the meanwhile, please let me know if I misunderstand the meaning of inline function or you have  any other ideas. thanks.
