### ISSUE TITLE
the warning message of unused variable.

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-pic#75]
bufferSize looks like an unused variable.  Would you mind removing it if it is an unused variable? thanks.

/home/iotlab/scofield/_workspace/-porting/kvs-pic/src/utils/src/TimerQueue.c: In function 'timerQueueGetTimersWithCustomData':
/home/iotlab/scofield/_workspace/-porting/kvs-pic/src/utils/src/TimerQueue.c:238:39: error: unused variable 'bufferSize' [-Werror=unused-variable]
     UINT32 timerId, timerIdCount = 0, bufferSize = 0;
                                       ^~~~~~~~~~
cc1: all warnings being treated as errors

https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/src/TimerQueue.c#L238

**Comment by ycyang1229** [comment]
other warning messages for syntax.



iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ make
[ 29%] Built target kvspicUtils
Scanning dependencies of target kvspicState
[ 30%] Building C object CMakeFiles/kvspicState.dir/src/state/src/State.c.o
[ 31%] Linking C static library libkvspicState.a
[ 31%] Built target kvspicState
Scanning dependencies of target kvspicClient
[ 32%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/AckParser.c.o
[ 33%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/AuthIntegration.c.o
[ 34%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/Callbacks.c.o
[ 35%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/Client.c.o
[ 36%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/ClientEvent.c.o
[ 38%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/ClientState.c.o
[ 39%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/FrameOrderCoordinator.c.o
[ 40%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/InputValidator.c.o
[ 41%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/Stream.c.o
[ 42%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/StreamEvent.c.o
[ 43%] Building C object CMakeFiles/kvspicClient.dir/src/client/src/StreamState.c.o
[ 44%] Linking C static library libkvspicClient.a
[ 44%] Built target kvspicClient
Scanning dependencies of target kvspic
[ 45%] Building C object CMakeFiles/kvspic.dir/src/client/src/AckParser.c.o
[ 46%] Building C object CMakeFiles/kvspic.dir/src/client/src/AuthIntegration.c.o
[ 47%] Building C object CMakeFiles/kvspic.dir/src/client/src/Callbacks.c.o
[ 48%] Building C object CMakeFiles/kvspic.dir/src/client/src/Client.c.o
[ 50%] Building C object CMakeFiles/kvspic.dir/src/client/src/ClientEvent.c.o
[ 51%] Building C object CMakeFiles/kvspic.dir/src/client/src/ClientState.c.o
[ 52%] Building C object CMakeFiles/kvspic.dir/src/client/src/FrameOrderCoordinator.c.o
[ 53%] Building C object CMakeFiles/kvspic.dir/src/client/src/InputValidator.c.o
[ 54%] Building C object CMakeFiles/kvspic.dir/src/client/src/Stream.c.o
[ 55%] Building C object CMakeFiles/kvspic.dir/src/client/src/StreamEvent.c.o
[ 56%] Building C object CMakeFiles/kvspic.dir/src/client/src/StreamState.c.o
[ 57%] Building C object CMakeFiles/kvspic.dir/src/duration/src/Duration.c.o
[ 58%] Building C object CMakeFiles/kvspic.dir/src/heap/src/AivHeap.c.o
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/AivHeap.c:12:48: error: missing braces around initializer [-Werror=missing-braces]
     struct AIV_ALLOCATION_HEADER gAivHeader = {{0, AIV_ALLOCATION_TYPE, ALLOCATION_FLAGS_FREE}, 0, NULL, NULL};
                                                ^
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/AivHeap.c:12:48: note: (near initialization for 'gAivHeader.header')
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/AivHeap.c:12:47: error: missing braces around initializer [-Werror=missing-braces]
     struct AIV_ALLOCATION_HEADER gAivHeader = {{0, AIV_ALLOCATION_TYPE, ALLOCATION_FLAGS_FREE}, 0, NULL, NULL};
                                               ^
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/AivHeap.c:12:47: note: (near initialization for 'gAivHeader')
cc1: all warnings being treated as errors
CMakeFiles/kvspic.dir/build.make:237: recipe for target 'CMakeFiles/kvspic.dir/src/heap/src/AivHeap.c.o' failed
make[2]: *** [CMakeFiles/kvspic.dir/src/heap/src/AivHeap.c.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/kvspic.dir/all' failed
make[1]: *** [CMakeFiles/kvspic.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ vim ../src/heap/src/AivHeap.c 
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ make
[ 29%] Built target kvspicUtils
[ 31%] Built target kvspicState
[ 44%] Built target kvspicClient
Scanning dependencies of target kvspic
[ 45%] Building C object CMakeFiles/kvspic.dir/src/heap/src/AivHeap.c.o
[ 46%] Building C object CMakeFiles/kvspic.dir/src/heap/src/Common.c.o
[ 47%] Building C object CMakeFiles/kvspic.dir/src/heap/src/Heap.c.o
[ 48%] Building C object CMakeFiles/kvspic.dir/src/heap/src/HybridHeap.c.o
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/HybridHeap.c:15:37: error: missing braces around initializer [-Werror=missing-braces]
     ALLOCATION_HEADER gVramHeader = {0, VRAM_ALLOCATION_TYPE, 0};
                                     ^
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/HybridHeap.c:15:37: note: (near initialization for 'gVramHeader')
cc1: all warnings being treated as errors
CMakeFiles/kvspic.dir/build.make:276: recipe for target 'CMakeFiles/kvspic.dir/src/heap/src/HybridHeap.c.o' failed
make[2]: *** [CMakeFiles/kvspic.dir/src/heap/src/HybridHeap.c.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/kvspic.dir/all' failed
make[1]: *** [CMakeFiles/kvspic.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ make
[ 29%] Built target kvspicUtils
[ 31%] Built target kvspicState
[ 44%] Built target kvspicClient
[ 45%] Building C object CMakeFiles/kvspic.dir/src/heap/src/HybridHeap.c.o
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/HybridHeap.c:15:37: error: missing braces around initializer [-Werror=missing-braces]
     ALLOCATION_HEADER gVramHeader = {0, VRAM_ALLOCATION_TYPE, 0};
                                     ^
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/HybridHeap.c:15:37: note: (near initialization for 'gVramHeader')
cc1: all warnings being treated as errors
CMakeFiles/kvspic.dir/build.make:276: recipe for target 'CMakeFiles/kvspic.dir/src/heap/src/HybridHeap.c.o' failed
make[2]: *** [CMakeFiles/kvspic.dir/src/heap/src/HybridHeap.c.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/kvspic.dir/all' failed
make[1]: *** [CMakeFiles/kvspic.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ vim ../src/heap/src/HybridHeap.c 
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ vim ../src/heap/src/HybridHeap.c 
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ make
[ 29%] Built target kvspicUtils
[ 31%] Built target kvspicState
[ 44%] Built target kvspicClient
Scanning dependencies of target kvspic
[ 45%] Building C object CMakeFiles/kvspic.dir/src/heap/src/HybridHeap.c.o
[ 46%] Building C object CMakeFiles/kvspic.dir/src/heap/src/SystemHeap.c.o
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/SystemHeap.c:15:36: error: missing braces around initializer [-Werror=missing-braces]
     ALLOCATION_HEADER gSysHeader = {0, SYS_ALLOCATION_TYPE, 0};
                                    ^
/home/iotlab/scofield/_workspace/*****-porting/kvs-pic/src/heap/src/SystemHeap.c:15:36: note: (near initialization for 'gSysHeader')
cc1: all warnings being treated as errors
CMakeFiles/kvspic.dir/build.make:289: recipe for target 'CMakeFiles/kvspic.dir/src/heap/src/SystemHeap.c.o' failed
make[2]: *** [CMakeFiles/kvspic.dir/src/heap/src/SystemHeap.c.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/kvspic.dir/all' failed
make[1]: *** [CMakeFiles/kvspic.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ vim ../src/heap/src/SystemHeap.c 
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ make
[ 29%] Built target kvspicUtils
[ 31%] Built target kvspicState
[ 44%] Built target kvspicClient
Scanning dependencies of target kvspic
[ 45%] Building C object CMakeFiles/kvspic.dir/src/heap/src/SystemHeap.c.o
[ 46%] Building C object CMakeFiles/kvspic.dir/src/mkvgen/src/MkvGenerator.c.o
[ 47%] Building C object CMakeFiles/kvspic.dir/src/mkvgen/src/MkvStatics.c.o
[ 48%] Building C object CMakeFiles/kvspic.dir/src/mkvgen/src/NalAdapter.c.o
[ 50%] Building C object CMakeFiles/kvspic.dir/src/mkvgen/src/SpsParser.c.o
[ 51%] Building C object CMakeFiles/kvspic.dir/src/state/src/State.c.o
[ 52%] Building C object CMakeFiles/kvspic.dir/src/trace/src/TraceProfiler.c.o
[ 53%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Allocators.c.o
[ 54%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Atomics.c.o
[ 55%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Base64.c.o
[ 56%] Building C object CMakeFiles/kvspic.dir/src/utils/src/BitField.c.o
[ 57%] Building C object CMakeFiles/kvspic.dir/src/utils/src/BitReader.c.o
[ 58%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Crc32.c.o
[ 59%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Directory.c.o
[ 60%] Building C object CMakeFiles/kvspic.dir/src/utils/src/DoubleLinkedList.c.o
[ 61%] Building C object CMakeFiles/kvspic.dir/src/utils/src/DynamicLibrary.c.o
[ 63%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Endianness.c.o
[ 64%] Building C object CMakeFiles/kvspic.dir/src/utils/src/FileIo.c.o
[ 65%] Building C object CMakeFiles/kvspic.dir/src/utils/src/FileLogger.c.o
[ 66%] Building C object CMakeFiles/kvspic.dir/src/utils/src/HashTable.c.o
[ 67%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Hex.c.o
[ 68%] Building C object CMakeFiles/kvspic.dir/src/utils/src/InstrumentedAllocators.c.o
[ 69%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Logger.c.o
[ 70%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Mutex.c.o
[ 71%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Semaphore.c.o
[ 72%] Building C object CMakeFiles/kvspic.dir/src/utils/src/SingleLinkedList.c.o
[ 73%] Building C object CMakeFiles/kvspic.dir/src/utils/src/StackQueue.c.o
[ 75%] Building C object CMakeFiles/kvspic.dir/src/utils/src/String.c.o
[ 76%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Tags.c.o
[ 77%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Thread.c.o
[ 78%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Time.c.o
[ 79%] Building C object CMakeFiles/kvspic.dir/src/utils/src/TimerQueue.c.o
[ 80%] Building C object CMakeFiles/kvspic.dir/src/utils/src/Version.c.o
[ 81%] Building C object CMakeFiles/kvspic.dir/src/view/src/ContentView.c.o
[ 82%] Linking C static library libkvspic.a
[100%] Built target kvspic
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ ll
total 828
drwxrwxr-x 3 iotlab iotlab   4096  七  22 11:03 ./
drwxrwxrwx 8 iotlab iotlab   4096  七  22 10:36 ../
-rw-rw-r-- 1 iotlab iotlab  15746  七  22 10:37 CMakeCache.txt
drwxrwxr-x 8 iotlab iotlab   4096  七  22 11:03 CMakeFiles/
-rw-rw-r-- 1 iotlab iotlab   4114  七  22 10:37 cmake_install.cmake
-rw-rw-r-- 1 iotlab iotlab 419998  七  22 11:03 libkvspic.a
-rw-rw-r-- 1 iotlab iotlab 158784  七  22 10:55 libkvspicClient.a
-rw-rw-r-- 1 iotlab iotlab    235  七  22 10:37 libkvspicClient.pc
-rw-rw-r-- 1 iotlab iotlab    211  七  22 10:37 libkvspic.pc
-rw-rw-r-- 1 iotlab iotlab   4166  七  22 10:55 libkvspicState.a
-rw-rw-r-- 1 iotlab iotlab    232  七  22 10:37 libkvspicState.pc
-rw-rw-r-- 1 iotlab iotlab 124394  七  22 10:47 libkvspicUtils.a
-rw-rw-r-- 1 iotlab iotlab    232  七  22 10:37 libkvspicUtils.pc
-rw-rw-r-- 1 iotlab iotlab  73950  七  22 10:37 Makefile
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ git status
On branch rtos-porting
Your branch is up to date with 'origin/rtos-porting'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ../CMakeLists.txt
	modified:   ../src/heap/src/AivHeap.c
	modified:   ../src/heap/src/HybridHeap.c
	modified:   ../src/heap/src/SystemHeap.c
	modified:   ../src/state/src/State.c
	modified:   ../src/utils/src/TimerQueue.c

no changes added to commit (use "git add" and/or "git commit -a")
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index aaee710..6004c5a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -22,6 +22,12 @@ option(RTOS_PATH "add the path of rtos." OFF)
 option(LIBC_PATH "add the path of libc." OFF)
 
 
+add_definitions(-fgnu89-inline)
+add_definitions(-Wno-pointer-to-int-cast)
+add_definitions(-Wno-int-to-pointer-cast)
+add_definitions(-Wno-implicit-function-declaration)
+
+
 ##
 ## code coverage.
 ##
diff --git a/src/heap/src/AivHeap.c b/src/heap/src/AivHeap.c
index 47a92af..70354a6 100644
--- a/src/heap/src/AivHeap.c
+++ b/src/heap/src/AivHeap.c
@@ -9,7 +9,7 @@
     struct AIV_ALLOCATION_HEADER gAivHeader = {{0, AIV_ALLOCATION_TYPE, ALLOCATION_FLAGS_FREE, ALLOCATION_HEADER_MAGIC}, 0, NULL, NULL};
     ALLOCATION_FOOTER gAivFooter = {0, ALLOCATION_FOOTER_MAGIC};
 #else
-    struct AIV_ALLOCATION_HEADER gAivHeader = {{0, AIV_ALLOCATION_TYPE, ALLOCATION_FLAGS_FREE}, 0, NULL, NULL};
+    struct AIV_ALLOCATION_HEADER gAivHeader = {{0, AIV_ALLOCATION_TYPE, {ALLOCATION_FLAGS_FREE}}, 0, NULL, NULL};
     ALLOCATION_FOOTER gAivFooter = {0};
 #endif
 
diff --git a/src/heap/src/HybridHeap.c b/src/heap/src/HybridHeap.c
index a4a1117..e0531ac 100644
--- a/src/heap/src/HybridHeap.c
+++ b/src/heap/src/HybridHeap.c
@@ -12,7 +12,7 @@
 #define VRAM_ALLOCATION_FOOTER_SIZE      SIZEOF(gVramFooter)
 
 #else
-    ALLOCATION_HEADER gVramHeader = {0, VRAM_ALLOCATION_TYPE, 0};
+    ALLOCATION_HEADER gVramHeader = {0, VRAM_ALLOCATION_TYPE, {0}};
     ALLOCATION_FOOTER gVramFooter = {0};
 
 #define VRAM_ALLOCATION_FOOTER_SIZE      0
diff --git a/src/heap/src/SystemHeap.c b/src/heap/src/SystemHeap.c
index 1ddf5f2..f6f9fad 100644
--- a/src/heap/src/SystemHeap.c
+++ b/src/heap/src/SystemHeap.c
@@ -12,7 +12,7 @@
 #define SYS_ALLOCATION_FOOTER_SIZE      SIZEOF(gSysFooter)
 
 #else
-    ALLOCATION_HEADER gSysHeader = {0, SYS_ALLOCATION_TYPE, 0};
+    ALLOCATION_HEADER gSysHeader = {0, SYS_ALLOCATION_TYPE, {0}};
     ALLOCATION_FOOTER gSysFooter = {0};
 
 #define SYS_ALLOCATION_FOOTER_SIZE      0
diff --git a/src/state/src/State.c b/src/state/src/State.c
index bbf9897..5a79a0c 100644
--- a/src/state/src/State.c
+++ b/src/state/src/State.c
@@ -138,11 +138,11 @@ STATUS stepStateMachine(PStateMachine pStateMachine)
     STATUS retStatus = STATUS_SUCCESS;
     PStateMachineState pState = NULL;
     UINT64 nextState, time;
-    UINT64 customData;
+    //UINT64 customData;
     PStateMachineImpl pStateMachineImpl = (PStateMachineImpl) pStateMachine;
 
     CHK(pStateMachineImpl != NULL, STATUS_NULL_ARG);
-    customData = pStateMachineImpl->customData;
+    //customData = pStateMachineImpl->customData;
 
     // Get the next state
     CHK(pStateMachineImpl->context.pCurrentState->getNextStateFn != NULL, STATUS_NULL_ARG);
diff --git a/src/utils/src/TimerQueue.c b/src/utils/src/TimerQueue.c
index 919c924..2ee6224 100644
--- a/src/utils/src/TimerQueue.c
+++ b/src/utils/src/TimerQueue.c
@@ -235,7 +235,7 @@ STATUS timerQueueGetTimersWithCustomData(TIMER_QUEUE_HANDLE handle, UINT64 custo
     STATUS retStatus = STATUS_SUCCESS;
     PTimerQueue pTimerQueue = FROM_TIMER_QUEUE_HANDLE(handle);
     BOOL locked = FALSE;
-    UINT32 timerId, timerIdCount = 0, bufferSize = 0;
+    UINT32 timerId, timerIdCount = 0;
 
     CHK(pTimerQueue != NULL && pTimerIdCount != NULL, STATUS_NULL_ARG);
 
iotlab@iotlab-Z390-AORUS-PRO-WIFI:~/scofield/_workspace/*****-porting/kvs-pic/build$

**Comment by MushMal** [comment]
Yes, these seem to be valid warnings and need to be addressed. Do you mind publishing a PR for these?

**Comment by ycyang1229** [comment]
I already detached my branch from this trunk, so left this work to the sdk team.  Closing it, thanks.
