### ISSUE TITLE
please add some check for header files.

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-pic#78]
Please add some checks for header files.
If you are interested in it, please refer this commit. https://github.com/ycyang1229/amazon-kinesis-video-streams-pic/commit/3a8369a2d6e58b63363c6e2b30f2de49471a78b6

Or you can close this issue. thanks.

**Comment by MushMal** [comment]
I am still unsure what the ask is. Do we make it cleaner doing the checks in a cross-platform cross-compiler fashion in the CMakeList.txt? What's the actual case here we are trying to solve?

**Comment by ycyang1229** [comment]
Yes, it is for cross-compiling. It is likes what we did in webrtc c sdk last time. I know the sdk's preference now, so I will close this. If you want me to create one pr likes the one in webrtc, I will do it. thanks. :)
