### ISSUE TITLE
Add MKV_PCM_xxx Codec IDs and H264_MULAW_MULTI Content Type to mkvgen include

### ISSUE THREAD

**Issue by dwaynehubbard** [awslabs/amazon-kinesis-video-streams-pic#86]
Add video/mkvgen/Include.h definitions for the use of PCM Codec IDs and "video/h264,audio/mulaw" Content Type

These are dependencies for the addition of a new amazon-kinesis-video-producer-c sample project that uses H264 video with a single PCM u-law audio track. Pull request to follow.

**Comment by MushMal** [comment]
I believe the definitions have been pushed. Closing the issue
