### ISSUE TITLE
calling Sign-In method from swift/Objective-C

### ISSUE THREAD

**Issue by vaihsd** [awslabs/amazon-kinesis-video-streams-pic#89]
Hi could anybody kindly let me know which function to call from Swift to SIGN-IN . I search for

src/client/src/Client.c
src/client/src/Stream.c
src/client/src/InputValidator.c
src/client/src/FrameOrderCoordinator.c
src/client/src/StreamEvent.c
amazon-kinesis-video-streams-pic/src/client/src/AuthIntegration.c
amazon-kinesis-video-streams-pic/src/client/src/

but could not find any FUNCTION to enter USERNAME and PASSWORD for signing into Kinesis Video stream. 
as mentioned before "The suggestions here will be helpful to all iOS developers".
 @lherman-cs @MushMal @amazon-auto

**Comment by MushMal** [comment]
@vaihsd the C/C++ layer requires an auth provider. Currently, we have a static, file and IoT based credential providers. Take a look at: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/source/IotAuthCallback.c for an IoT auth provider as an example if you would like to implement your own.

The sample that's included in the C producer uses the static auth provider. I am not sure what you mean by username/password. We use AWS credentials at the core of the auth. If you are referring to Cognito integration then you will need to integrate it yourself as we don't have a cognito provider.

I am going to resolve this issue as non-specific.
